const data = {
    products: [
      {
        _id: '1',
        name: 'Cây trầu bà cột chậu xi măng trụ vuông',
        slug: 'cay-trau-ba',
        category: 'outDoor',
        image: '/images/p1.jpg', // 679px × 829px
        price: 160000,
        countInStock: 0,
        rating: 4.5,
        numReviews: 10,
        description: 'Có tác dụng thanh lọc không khí trong nhà mà còn chứa đựng ý nghĩa phong thủy rất tốt, mang dáng vẻ thanh lịch và sang trọng.',
      },
      {
        _id: '2',
        name: 'Cây cọ lá xẻ mini để bàn chậu sứ hoa văn',
        slug: 'cay-co-la-xe',
        category: 'inDoor',
        image: '/images/p2.jpg',
        price: 250000,
        countInStock: 20,
        rating: 4.0,
        numReviews: 10,
        description: 'Cây cọ nhật là loại cây trong nhà có kiểu lá xòe rộng như những cánh quạt, giúp trang trí không gian thêm xanh mát. Nó còn là loại cây phong thủy tượng trưng cho sự giàu sang và tiền tài nên rất đáng trồng trên bàn làm việc.',
      },
      {
        _id: '3',
        name: 'Cây hồng môn cỡ nhỏ chậu sứ trắng',
        slug: 'cay-hong-mon',
        category: 'inDoor',
        image: '/images/p3.jpg',
        price: 240000,
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: 'Cây hồng môn được biết tới là một loại cây cảnh mang lại điều tốt lành, có thể giúp điều hòa khí phong thủy trong nhà, có khả năng thu hút những dòng khí tích cực và làm tiêu bớt dòng khí tiêu cực cho môi trường xung quanh, trồng cây hồng môn trong nhà sẽ giúp không gian sống trở nên hài hòa và bình yên hơn.',
      },
      {
        _id: '4',
        name: 'Cây ngũ gia bì cẩm thạch nhỏ chậu ươm',
        slug: 'cay-ngu-vi-gia',
        category: 'inDoor',
        image: '/images/p4.jpg',
        price: 165000,
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'Ngũ gia bì là loại cây mang lại tài vận, thịnh vượng và may mắn, trồng trong nhà sẽ mang đến một không gian thư thái, trong lành cho gia đình.',
      },
    ],
  };
  export default data;